#!/usr/bin/env bash
# Regenerate docs/backlog/INDEX.md from YAML frontmatter in every
# docs/backlog/**/*.md. Stable ordering: same input → same output bytes.
#
# Groups by milestone (V3 / M4 / M3 / M2 / M1 / Unassigned / Closed) →
# phase → severity → opened-desc. Closed items go to a bottom section
# regardless of milestone.
#
# Usage:
#   scripts/backlog-index.sh              # writes docs/backlog/INDEX.md
#   BACKLOG_DIR=<path> scripts/backlog-index.sh --out <path>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOST_IO_GUARD="${HOST_IO_GUARD:-$SCRIPT_DIR/memd-host-io-guard.sh}"
if [ "${HOST_IO_GUARD_ENABLED:-1}" != "0" ] && [ "${HOST_IO_GUARD_ENABLED:-1}" != "false" ]; then
  "$HOST_IO_GUARD"
fi

BACKLOG_DIR="${BACKLOG_DIR:-docs/backlog}"
OUT="$BACKLOG_DIR/INDEX.md"

while [ $# -gt 0 ]; do
    case "$1" in
        --out) OUT="$2"; shift 2 ;;
        *) echo "unknown arg: $1" >&2; exit 2 ;;
    esac
done

# Extract frontmatter value from $f for $key.
fm_get() {
    local f="$1" key="$2"
    awk -v key="$key" '
        BEGIN { in_fm=0 }
        NR==1 && /^---$/ { in_fm=1; next }
        in_fm && /^---$/ { exit }
        in_fm && $0 ~ "^"key":" {
            sub(/^[^:]+:[[:space:]]*/, "")
            print
            exit
        }
    ' "$f"
}

# Extract title from first "# Title" heading.
title_get() {
    local f="$1"
    awk '/^# / { sub(/^# /, ""); print; exit }' "$f"
}

# Map phase → milestone bucket.
milestone_of() {
    local phase="$1"
    case "$phase" in
        A3|B3|C3|D3|E3|F3) echo "V3" ;;
        I2|M2-evo|N2|K2|L2) echo "M4" ;;
        J2|O2|P2) echo "M3" ;;
        B2|C2|D2|E2|F2|G2|H2) echo "M2" ;;
        A2) echo "M1" ;;
        unassigned|"") echo "Unassigned" ;;
        *) echo "Other" ;;
    esac
}

# Severity rank (critical=1 highest, low=4 lowest).
sev_rank() {
    case "$1" in
        critical) echo 1 ;;
        high) echo 2 ;;
        medium) echo 3 ;;
        low) echo 4 ;;
        *) echo 5 ;;
    esac
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

find "$BACKLOG_DIR" -maxdepth 3 -name '*.md' -not -name 'INDEX.md' -not -name 'TEMPLATE.md' | sort | while read -r f; do
    status=$(fm_get "$f" status)
    severity=$(fm_get "$f" severity)
    phase=$(fm_get "$f" phase)
    opened=$(fm_get "$f" opened)
    title=$(title_get "$f")
    [ -z "$status" ] && status="unknown"
    [ -z "$severity" ] && severity="medium"
    [ -z "$phase" ] && phase="unassigned"
    [ -z "$title" ] && title=$(basename "$f" .md)
    milestone=$(milestone_of "$phase")
    sr=$(sev_rank "$severity")
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$milestone" "$phase" "$sr" "$severity" "$opened" "$status" "$f" "$title"
done > "$tmp"

# Now emit Markdown. Order:
#   V3 → M4 → M3 → M2 → M1 → Unassigned → Closed (all items where status=closed)
# Within milestone: sort by phase, then severity rank, then opened desc.

generated_ts="$(git log -1 --format=%cI docs/backlog 2>/dev/null || date -Iseconds)"
total=$(wc -l < "$tmp")

{
    echo "# Backlog Index"
    echo ""
    echo "> Generated by \`scripts/backlog-index.sh\` from YAML frontmatter."
    echo "> Do not edit by hand — edit the individual backlog files and regenerate."
    echo ""
    echo "**Total items:** $total"
    echo ""

    for ms in V3 M4 M3 M2 M1 Unassigned Other; do
        # Open items in this milestone
        section=$(awk -F'\t' -v ms="$ms" '$1==ms && $6!="closed"' "$tmp" \
            | sort -t $'\t' -k2,2 -k3,3n -k5,5r)
        if [ -n "$section" ]; then
            echo "## $ms"
            echo ""
            current_phase=""
            while IFS=$'\t' read -r _ phase _ severity opened status path title; do
                if [ "$phase" != "$current_phase" ]; then
                    echo ""
                    echo "### Phase \`$phase\`"
                    echo ""
                    current_phase="$phase"
                fi
                rel="${path#$BACKLOG_DIR/}"
                echo "- **[$severity]** [$title]($rel) — \`$status\` · opened $opened"
            done <<< "$section"
            echo ""
        fi
    done

    # Closed bottom section
    closed=$(awk -F'\t' '$6=="closed"' "$tmp" \
        | sort -t $'\t' -k1,1 -k2,2 -k5,5r)
    if [ -n "$closed" ]; then
        echo "## Closed"
        echo ""
        while IFS=$'\t' read -r ms phase _ severity opened _ path title; do
            rel="${path#$BACKLOG_DIR/}"
            echo "- **[$severity]** [$title]($rel) — \`$ms / $phase\` · opened $opened"
        done <<< "$closed"
        echo ""
    fi
} > "$OUT"

echo "backlog-index: wrote $OUT ($total items)"
