#!/usr/bin/env bash
# Rewrite docs/handoff/LATEST.md as a relative symlink to the newest
# YYYY-MM-DD-*.md handoff packet. Also regenerates docs/handoff/INDEX.md
# with date-desc list of every handoff.

set -euo pipefail

HANDOFF_DIR="${HANDOFF_DIR:-docs/handoff}"

if [ ! -d "$HANDOFF_DIR" ]; then
    echo "handoff-latest: no $HANDOFF_DIR directory" >&2
    exit 1
fi

# Primary key: date prefix (desc). Tie-break: mtime (desc) so same-day
# packets resolve to the most recently written one. Using -printf so we
# get `<mtime>\t<date>\t<path>` and sort on the first two fields.
newest=$(find "$HANDOFF_DIR" -maxdepth 1 -type f -name '[0-9][0-9][0-9][0-9]-*.md' \
    -not -name 'LATEST.md' -not -name 'INDEX.md' \
    -printf '%T@\t%f\t%p\n' \
    | awk -F'\t' '{ date=substr($2,1,10); print date "\t" $1 "\t" $3 }' \
    | sort -k1,1r -k2,2nr \
    | head -1 \
    | cut -f3)

if [ -z "$newest" ]; then
    echo "handoff-latest: no dated handoff packets found in $HANDOFF_DIR" >&2
    exit 1
fi

newest_base=$(basename "$newest")
ln -sfn "$newest_base" "$HANDOFF_DIR/LATEST.md"

# Regenerate INDEX.md
{
    echo "# Handoff Index"
    echo ""
    echo "> Generated by \`scripts/handoff-latest.sh\`. Do not edit by hand."
    echo ""
    echo "LATEST → \`$newest_base\`"
    echo ""
    find "$HANDOFF_DIR" -maxdepth 1 -type f -name '[0-9][0-9][0-9][0-9]-*.md' \
        -not -name 'LATEST.md' -not -name 'INDEX.md' \
        | sort -r | while read -r h; do
        base=$(basename "$h")
        title=$(awk '/^# / { sub(/^# /, ""); print; exit }' "$h")
        date=$(echo "$base" | sed 's/^\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).*/\1/')
        [ -z "$title" ] && title="$base"
        echo "- **$date** — [$title](./$base)"
    done
} > "$HANDOFF_DIR/INDEX.md"

count=$(find "$HANDOFF_DIR" -maxdepth 1 -type f -name '[0-9][0-9][0-9][0-9]-*.md' -not -name 'LATEST.md' -not -name 'INDEX.md' | wc -l)
echo "handoff-latest: LATEST.md → $newest_base; INDEX.md ($count entries)"
