#!/usr/bin/env bash
# Rewrite docs/handoff/LATEST.md as a relative symlink to the newest
# YYYY-MM-DD-*.md handoff packet. Also regenerates docs/handoff/INDEX.md
# with date-desc list of every handoff.

set -euo pipefail

HANDOFF_DIR="${HANDOFF_DIR:-docs/handoff}"

if [ ! -d "$HANDOFF_DIR" ]; then
    echo "handoff-latest: no $HANDOFF_DIR directory" >&2
    exit 1
fi

# Primary key: date prefix (desc). Tie-break: mtime (desc) so same-day
# packets resolve to the most recently written one. Keep this portable across
# GNU/Linux and macOS/BSD where `find -printf` is unavailable.
newest=$(python3 - "$HANDOFF_DIR" <<'PY'
from pathlib import Path
import sys

handoff_dir = Path(sys.argv[1])
packets = [
    p for p in handoff_dir.glob("[0-9][0-9][0-9][0-9]-*.md")
    if p.name not in {"LATEST.md", "INDEX.md"}
]
if packets:
    newest = max(packets, key=lambda p: (p.name[:10], p.stat().st_mtime))
    print(newest)
PY
)

if [ -z "$newest" ]; then
    echo "handoff-latest: no dated handoff packets found in $HANDOFF_DIR" >&2
    exit 1
fi

newest_base=$(basename "$newest")
ln -sfn "$newest_base" "$HANDOFF_DIR/LATEST.md"

# Regenerate INDEX.md
{
    echo "# Handoff Index"
    echo ""
    echo "> Generated by \`scripts/handoff-latest.sh\`. Do not edit by hand."
    echo ""
    echo "LATEST → \`$newest_base\`"
    echo ""
    python3 - "$HANDOFF_DIR" <<'PY'
from pathlib import Path
import sys

handoff_dir = Path(sys.argv[1])
packets = sorted(
    [
        p for p in handoff_dir.glob("[0-9][0-9][0-9][0-9]-*.md")
        if p.name not in {"LATEST.md", "INDEX.md"}
    ],
    key=lambda p: p.name,
    reverse=True,
)
for packet in packets:
    title = ""
    for line in packet.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            title = line[2:]
            break
    if not title:
        title = packet.name
    date = packet.name[:10]
    print(f"- **{date}** — [{title}](./{packet.name})")
PY
} > "$HANDOFF_DIR/INDEX.md"

count=$(python3 - "$HANDOFF_DIR" <<'PY'
from pathlib import Path
import sys

handoff_dir = Path(sys.argv[1])
print(len([
    p for p in handoff_dir.glob("[0-9][0-9][0-9][0-9]-*.md")
    if p.name not in {"LATEST.md", "INDEX.md"}
]))
PY
)
echo "handoff-latest: LATEST.md → $newest_base; INDEX.md ($count entries)"
